export const TYPES = {
  AnswerRepository: Symbol("AnswerRepository"),
  AttendanceRepository: Symbol("AttendanceRepository"),
  CampusRepository: Symbol("CampusRepository"),
  DonationRepository: Symbol("DonationRepository"),
  DonationBatchRepository: Symbol("DonationBatchRepository"),
  FormRepository: Symbol("FormRepository"),
  FormSubmissionRepository: Symbol("FormSubmissionRepository"),
  FundDonationRepository: Symbol("FundDonationRepository"),
  FundRepository: Symbol("FundRepository"),
  GroupMemberRepository: Symbol("GroupMemberRepository"),
  GroupRepository: Symbol("GroupRepository"),
  GroupServiceTimeRepository: Symbol("GroupServiceTimeRepository"),
  HouseholdRepository: Symbol("HouseholdRepository"),
  NoteRepository: Symbol("NoteRepository"),
  PersonRepository: Symbol("PersonRepository"),
  QuestionRepository: Symbol("QuestionRepository"),
  ServiceRepository: Symbol("ServiceRepository"),
  ServiceTimeRepository: Symbol("ServiceTimeRepository"),
  SessionRepository: Symbol("SessionRepository"),
  VisitRepository: Symbol("VisitRepository"),
  VisitSessionRepository: Symbol("VisitSessionRepository"),
  LoggerService: Symbol("LoggerService"),
  Repositories: Symbol("Repositories")
};
